### ISSUE TITLE
Development Workflow

### ISSUE THREAD

**Issue by czgdp1807** [phemeiitjodhpur/phemeiitjodhpur.github.io#5]
Please answer the following questions:

1. Are there any plans for developing the website further?
2. Is it good to add, PULL_REQUEST_TEMPLATE.md?
3. Is it possible to shift to jekyll or some other framework which supports static websites?

**Comment by NiveditJain** [comment]
1) Yes, there are many future plans for development.
2) We will add it soon
3) In future, we are planning some dynamic features also so Jekyll doesn`t seem to be an option. Soon we are planning to set up a backend team too.
